TargetRubyVersion: "2.0"

AllCops:
  Exclude:
    - spec/**/*

Style/RedundantSelf:
  Enabled: false

Metrics/ClassLength:
  Max: 500

# We're not living in the 90's anymore, people can deal with long lines
Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassCheck:
  Enabled: false
