sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler
install: bundle install --path vendor/bundle
script: 
  - bundle exec rake test
deploy:
  provider: rubygems
  api_key:
    secure: KEY_HERE
  gem: rubocop-require_tools
  on:
    branch: master
    repo: milch/rubocop-require_tools
